# Generated by Django 5.2.8 on 2025-11-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_jobs_job_title_84d156_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_city_country',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_title_0e1e41_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'company'], name='jobs_job_title_84d156_idx'),
        ),
    ]
